name: Deploy Infrastructure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sentinel
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Plan
        run: |
          cd terraform
          terraform init
          terraform plan -input=false -var-file=env.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: |
          cd terraform
          terraform init
          terraform apply -input=false -var-file=env.tfvars -auto-approve